# Site settings
title: Binghuan Lin's Home Page
email: binghuan.lin@hotmail.com
url: https://quantbhlin.github.io
description: "Research Portfolio of Binghuan Lin, dive deep into the world of economics and finance"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Binghuan Lin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://fi.linkedin.com/in/binghuanlin/en
  - title: bitbucket
    url: https://bitbucket.org/quantbhlin/
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
