# Site settings
title: Binghuan Lin's Home Page
email: binghuan.lin@hotmail.com
url: https://www.bhlin.me
description: "Research Portfolio of Binghuan Lin, dive deep into the world of economics and finance"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Binghuan Lin

gems:
  - jekyll-sitemap

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://fi.linkedin.com/in/binghuanlin/en
  - title: bitbucket
    url: https://bitbucket.org/quantbhlin/
  - title: SSRN
    url: http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=2190200
  - title: zhihu
    url: http://www.zhihu.com/people/bh-lin
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
